
site_name: TFO Docs

theme:
  logo: assets/logo.png
  favicon: images/favicon.ico
  name: "material"



  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

features:
  - navigation.top
  - toc.follow
  - header.autohide

nav:
  - intro: intro.md
  - index: index.md
  - TestPage: testpage.md
  - Role guide: RoleGuide.md
  - Full rulebook: rulebook.md
  - Rules: rules.md
  - LoadoutFull: LoadoutFull.md
  - Role Guide:
    - PLatoonleader: pltleader.md
    - medic: medic.md
    
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css
