
site_name: TFO Docs

theme:
  logo: assets/logo.png
  favicon: images/favicon.ico
  name: "material"


  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

features:
  - navigation.top
  - toc.follow
  - header.autohide
  - navigation.footer


nav:
  - Intro: index.md
  - Basics: basics.md
  - TFO's Rulebook: rulebook.md
  - LoadoutFull: LoadoutFull.md
  - Our team: team.md
  - Ranks: ranks.md
  - Role Guide:
    - Platoon leader: RoleGuide/pltleader.md
    - Squad leader: RoleGuide/sql.md
    - Medic: RoleGuide/medic.md
    - CLS: RoleGuide/cls.md
    - Rifleman + LAT: RoleGuide/rifleman.md
    - AA: RoleGuide/AA.md
    - AA2: RoleGuide/AA2.md
    - AA3: RoleGuide/AA3.md
    - AA4: RoleGuide/AA4.md
    - Auto Rifleman: RoleGuide/AR.md
    - Anti Tank: RoleGuide/AT.md
    - Marksmen: RoleGuide/marksmen.md
    - Engineer: RoleGuide/eod.md
    - Grenadier: RoleGuide/grenadier.md
    

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css


copyright: Copyright &copy; 2016 - 2023 Task Force Omega
